name: plant_health_data
description: "App to collect leaf data"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path: ^1.9.0
  excel: ^4.0.6
  path_provider: ^2.1.4
  animated_bottom_navigation_bar: ^1.3.3
  multi_select_flutter: ^4.1.3
  location: ^6.0.2
  loading_animation_widget: ^1.3.0
  latlong2: ^0.9.1
  intl: ^0.19.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - 'assets/sample_images/youngLeavesChlorosis.webp'
    - 'assets/sample_images/oldLeavesChlorosis.jpg'
    - 'assets/sample_images/entirePlantChlorosis.webp'
    - 'assets/sample_images/leavesEdgeChlorosis.jpg'
    - 'assets/sample_images/spotsChlorosis.jpg'
    - 'assets/sample_images/leavesTipChlorosis.jpg'
    - 'assets/sample_images/completeInterveinalChlorosis.jpg'
    - 'assets/sample_images/partialInterveinalChlorosis.jpg'
    - 'assets/sample_images/leavesVeinChlorosis.webp'
    - 'assets/sample_images/deepGreenYoungLeaves.webp'
    - 'assets/sample_images/paleGreenLeaves.webp'
    - 'assets/sample_images/rollCurlingLeaves.jpg'
    - 'assets/sample_images/flaccidLeaves.jpg'
    - 'assets/sample_images/witchesBroom.webp'
    - 'assets/sample_images/dieback.jpg'
    - 'assets/sample_images/leavesEdgeBrownAsh.webp'
    - 'assets/sample_images/spotsBrownAsh.jpg'
    - 'assets/sample_images/leavesTipBrownAsh.jpg'
    - 'assets/sample_images/leavesEdgeRedPurple.jpg'
    - 'assets/sample_images/spotsRedPurple.jpg'
    - 'assets/sample_images/leavesTipRedPurple.webp'
    - 'assets/sample_images/leavesVeinRedPurple.jpg'

    - 'assets/plant_health_data.xlsx'

    - 'assets/magazine_images/plant_art1.png'

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 400
